### ISSUE TITLE
"Similarity" search for `'a list -> 'a` in FCS causes an exception

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsdn-projects/FSDN#12] opened 2016-06-13 12:11 UTC
![image](https://cloud.githubusercontent.com/assets/873919/16007058/06f2c202-3179-11e6-9e50-dc9ea9340070.png)

**Comment by yukitos** [comment] 2016-06-13 12:57
Thank you for the report.
I heard from @hafuu that the root cause of this issue has already been fixed in the latest version of FSharpApiSearch (FYI: [this code](https://github.com/hafuu/FSharpApiSearch/commit/ce7b4d6fd07a168d941f5159844306c97723b2c6#diff-68664738fef90f434c07fc7a32a571daR683)).
So this will be fixed very soon.

**Closed as completed** 2016-06-14 05:35 UTC
